### PR TITLE
feat: fix dark mode titles and chart colors

### LINKED ISSUE #60: Dark Mode fixes for Shutdown Details
The "before" shutdown colors + title text should be white in dark mode.

### PR DESCRIPTION
**Pull request by skaplan-dev**
## Motivation
- Closes #60 

## Changes
- Before
Screenshot 2024-05-27 at 7 25 30 PM
- After
Screenshot 2024-05-27 at 7 23 47 PM

### CODE REVIEW

File: src/components/charts/AggregateLineChart.tsx [hunk 1]
```diff
@@ -60,7 +60,9 @@ export const AggregateLineChart: React.FC<AggregateLineProps> = ({
             label: 'Before shutdown',
             fill: false,
             tension: 0.1,
-            pointBackgroundColor: CHART_COLORS.GREY,
+            borderColor: darkMode ? '#94a3b8' : '#c8cbcf',
+            backgroundColor: darkMode ? '#94a3b8' : '#c8cbcf',
+            pointBackgroundColor: darkMode ? 'white' : CHART_COLORS.GREY,
```
Comment (devinmatte) [inline src/components/charts/AggregateLineChart.tsx:65]: Ideally we should add all these colors to the enum CHART_COLORS

**Review by devinmatte — APPROVED** [review]

File: src/components/charts/AggregateLineChart.tsx (hunk 1 above)
Comment (skaplan-dev) [reply src/components/charts/AggregateLineChart.tsx:65]: yeah some of them are just default chartjs colors 🤷
